# Generated by Django 5.0.4 on 2024-04-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "legislative_data",
            "0002_person_alter_bill_primary_sponsor_vote_voteresult_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="voteresult",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
