# Generated by Django 5.0.4 on 2024-04-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "legislative_data",
            "0003_alter_bill_id_alter_person_id_alter_vote_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="primary_sponsor",
            new_name="sponsor_id",
        ),
    ]
